apiVersion: v1
items:
- apiVersion: traefik.containo.us/v1alpha1
  kind: Middleware
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"traefik.containo.us/v1alpha1","kind":"Middleware","metadata":{"annotations":{},"name":"java-strip","namespace":"hydra-infra"},"spec":{"stripPrefix":{"prefixes":["/java"]}}}
    creationTimestamp: "2026-02-09T22:30:16Z"
    generation: 1
    name: java-strip
    namespace: hydra-infra
    resourceVersion: "7157721"
    uid: 6c3f1b8e-5018-4779-a19e-fe44226a4107
  spec:
    stripPrefix:
      prefixes:
      - /java
- apiVersion: traefik.containo.us/v1alpha1
  kind: Middleware
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"traefik.containo.us/v1alpha1","kind":"Middleware","metadata":{"annotations":{},"name":"jflap-strip","namespace":"hydra-infra"},"spec":{"stripPrefix":{"prefixes":["/jflap"]}}}
    creationTimestamp: "2026-02-09T21:15:45Z"
    generation: 1
    name: jflap-strip
    namespace: hydra-infra
    resourceVersion: "7136645"
    uid: 16c23152-73e4-4623-8fe5-3196403bfae6
  spec:
    stripPrefix:
      prefixes:
      - /jflap
- apiVersion: traefik.containo.us/v1alpha1
  kind: Middleware
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"traefik.containo.us/v1alpha1","kind":"Middleware","metadata":{"annotations":{},"name":"hydra-forward-auth","namespace":"hydra-system"},"spec":{"forwardAuth":{"address":"http://hydra-auth.hydra-system.svc.cluster.local:6969/auth/verify","authResponseHeaders":["X-Hydra-User","X-Hydra-Email"],"trustForwardHeader":true}}}
    creationTimestamp: "2026-01-30T21:48:29Z"
    generation: 1
    name: hydra-forward-auth
    namespace: hydra-system
    resourceVersion: "3821839"
    uid: c35ccf39-eaf6-4ed1-a023-12341d6b0d16
  spec:
    forwardAuth:
      address: http://hydra-auth.hydra-system.svc.cluster.local:6969/auth/verify
      authResponseHeaders:
      - X-Hydra-User
      - X-Hydra-Email
      trustForwardHeader: true
kind: List
metadata:
  resourceVersion: ""
