apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"traefik","namespace":"hydra-system"}}
  creationTimestamp: "2026-01-19T14:35:48Z"
  name: traefik
  namespace: hydra-system
  resourceVersion: "5443"
  uid: b883b3da-3a20-4556-9cbd-3d57d5062229
