apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"traefik"},"name":"traefik","namespace":"hydra-system"},"spec":{"ports":[{"name":"web","nodePort":30080,"port":80,"targetPort":"web"},{"name":"websecure","nodePort":30443,"port":443,"targetPort":"websecure"},{"name":"hydra","nodePort":30969,"port":6969,"targetPort":"hydra"}],"selector":{"app.kubernetes.io/name":"traefik"},"type":"NodePort"}}
  creationTimestamp: "2026-01-19T14:35:50Z"
  labels:
    app.kubernetes.io/name: traefik
  name: traefik
  namespace: hydra-system
  resourceVersion: "5474"
  uid: 20d69743-8e77-440f-bd7d-96166ea9cdb8
spec:
  clusterIP: 10.43.143.77
  clusterIPs:
  - 10.43.143.77
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: web
    nodePort: 30080
    port: 80
    protocol: TCP
    targetPort: web
  - name: websecure
    nodePort: 30443
    port: 443
    protocol: TCP
    targetPort: websecure
  - name: hydra
    nodePort: 30969
    port: 6969
    protocol: TCP
    targetPort: hydra
  selector:
    app.kubernetes.io/name: traefik
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
