# renew_before_expiry = 30 days
version = 5.0.0
archive_dir = /etc/letsencrypt/archive/hydra.newpaltz.edu
cert = /etc/letsencrypt/live/hydra.newpaltz.edu/cert.pem
privkey = /etc/letsencrypt/live/hydra.newpaltz.edu/privkey.pem
chain = /etc/letsencrypt/live/hydra.newpaltz.edu/chain.pem
fullchain = /etc/letsencrypt/live/hydra.newpaltz.edu/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 9cc44352277e78c37cd58fffa143b32d
authenticator = webroot
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
pref_challs = http-01,
webroot_path = /var/www/html
[acme_renewal_info]
ari_retry_after = 2026-01-17T21:26:02

[[webroot]]
hydra.newpaltz.edu = /var/www/html
gpt.hydra.newpaltz.edu = /var/www/html
n8n.hydra.newpaltz.edu = /var/www/html
