apiVersion: kubeai.org/v1
kind: Model
metadata:
  name: deepseek-r1-distill-qwen-14b
  namespace: kubeai
spec:
  features: [TextGeneration]
  owner: deepseek-ai
  url: "hf://deepseek-ai/DeepSeek-R1-Distill-Qwen-14B"
  engine: VLLM
  args:
    - "--max-model-len=8192"
    - "--gpu-memory-utilization=0.90"
    - "--dtype=auto"
  resourceProfile: nvidia-rtx-3090:1
  minReplicas: 0
