apiVersion: kubeai.org/v1
kind: Model
metadata:
  name: granite-3-3-8b-instruct
  namespace: kubeai
spec:
  features: [TextGeneration]
  owner: ibm-granite
  url: "hf://ibm-granite/granite-3.3-8b-instruct"
  engine: VLLM
  args:
    - "--max-model-len=8192"
    - "--gpu-memory-utilization=0.90"
    - "--dtype=auto"
  resourceProfile: nvidia-rtx-3090:1
  minReplicas: 0
