apiVersion: kubeai.org/v1
kind: Model
metadata:
  name: qwen-2-5-7b-instruct
  namespace: kubeai
spec:
  features: [TextGeneration]
  owner: Qwen
  url: "hf://Qwen/Qwen2.5-7B-Instruct"
  engine: VLLM
  args:
    - "--max-model-len=8192"
    - "--gpu-memory-utilization=0.90"
    - "--dtype=auto"
  resourceProfile: nvidia-rtx-3090:1
  minReplicas: 0
