# Docker Compose for NewPaltz CS Lab Website
# React frontend + Express backend + MariaDB

services:
  # Backend API (serves both API and static frontend)
  backend:
    build: .
    container_name: cs-lab-backend
    environment:
      - NODE_ENV=production
      - PORT=5001
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=${DB_USER:-cslab}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME:-cslab}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "5001:5001"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - cslab-network
      - hydra_students_net

  # MariaDB Database
  db:
    image: mariadb:10.11
    container_name: cs-lab-db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME:-cslab}
      - MYSQL_USER=${DB_USER:-cslab}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - cslab-network

volumes:
  db_data:

networks:
  cslab-network:
    driver: bridge
  hydra_students_net:
    external: true
