services:
  sshpiper:
    image: farmer1992/sshpiperd:latest
    container_name: sshpiper
    ports:
      - "2222:2222"
    volumes:
      # sshpiper working directory with upstream configs
      - ./config:/var/sshpiper
      # SSH keys for authentication (read-only)
      - ../data/ssh-keys:/ssh-keys:ro
    networks:
      - hydra_students_net
    restart: unless-stopped
    command: /sshpiperd/plugins/workingdir --root /var/sshpiper --no-check-perm
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2222"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  hydra_students_net:
    external: true
