apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openwebui-data-nfs
  namespace: hydra-infra
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: hydra-nfs
